import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavbarDemo } from "@/components/Navbar";
import Footer from "@/components/Footer";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nishanthan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.variable}  antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full overflow-hidden   dark:bg-black scroll-smooth">
            {/* --- NAVBAR HERE --- */}
            <NavbarDemo />

            {/* --- PAGE CONTENT HERE --- */}
            {children}

            {/* --- FOOTER HERE --- */}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
