import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavbarDemo } from "@/components/Navbar";
import Footer from "@/components/Footer";
import Image from "next/image";
import { Toaster } from "sonner";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nishanthan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className}  antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <div className="w-full overflow-hidden relative  dark:bg-black scroll-smooth ">
            {/* --- NAVBAR HERE --- */}
            <NavbarDemo />
            <div className="absolute max-h-screen inset-0 pointer-events-none">
              <Image
                src="/paperlast1.png"
                alt="footer background"
                fill
                className="object-cover  dark:opacity-45"
                priority
              />
            </div>
            <div className=" max-h-screen from-background to-background/80 pointer-events-none absolute from-10%  inset-0 bg-linear-to-t via-transparent dark:from-black dark:to-black" />

            {/* --- PAGE CONTENT HERE --- */}
            <div className="relative z-10">
              {children}

              {/* --- FOOTER HERE --- */}
              <Footer />
            </div>
          </div>
          <Toaster
            richColors // optional: allows custom colors per theme
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
